### ISSUE TITLE
Loomio e plebiscito

### ISSUE THREAD

**Issue by desci** [piratas/gti#16]
Está criado um [grupo no  loomio](https://www.loomio.org/g/JDmI4ZKv/partido-pirata-no-brasil-pirate-party-in-brazil-gti) para o GTI, acessível através de `gti.pirata.xyz/loomio/` (e temporariamente diretamente em `gti.pirata.xyz` também).

A ideia original era pegar os e-mails inscritos no [formulário que o GTC fez](http://partidopirata.org/chamada-aberta-para-os-grupos-de-trabalho/) e adicionar os e-mails das pessoas lá. Já pedi pro cara do GTC fazer isto, mas surgiu outra questão, que eu trago pra apreciação do maior número possível de pessoas (já que este texto aqui vai parar no taiga e no telegram, além do github).

Eu entendo (e algumas outras pessoas provavelmente também) que para além do método proposto com o auxílio do GTC para entrada no GTI agora em 2016, é importante valorizar o esforço das pessoas que podem não ter se inscrito no formulário mas comparareceram em reuniões, fizeram (e tentaram fazer) coisas para o GTI, entraram no grupo do Telegram, na organização do Github, etc.

Eu pessoalmente considero legítimo dizer que estas pessoas demonstraram intenção de fazer parte do GTI, talvez até mais pragmaticamente do que a simbologia de preencher um formulário (em um site com falhas de segurança, que se registre).

A ideia do grupo do Loomio era servir para fazer deliberações, como por exemplo, mas não necessariamente, a escolha de articulador que deve ser feita dia 1º de maio.

Além disto também deveria servir como mais um canal de aglutinação para além do github, que aparentemente foi o que juntou mais gente por enquanto.

Por enquanto o grupo no Loomio segue a proposta original de adicionar somente os e-mails que se inscreveram no formulário supracitado, o que ainda não foi feito.

Opiniões?

**Comment by pbaesse** [comment]
Acredito que, mesmo sem o formulário, qualquer que queria ajudar poderia e deveria ajudar das maneiras mais simples possível.

**Comment by desci** [comment]
@pbaesse Isto está previsto inclusive no regimento.
Eu pessoalmente critiquei o tal formulário do gtc desde o começo e acredito que as pessoas envolvidas no processo deveriam tar decisões.
Baixou a participação (de novo) no entanto.
Não sei se as pessoas estão entendendo que é um processo de formalização acontecendo.

**Comment by desci** [comment]
Pela [reunião de 1º de maio](https://www.loomio.org/d/tCudFTOJ/relatoria-reuni-o-gti-1-de-maio-de-2016), resolvi seguir o meu conselho e as considerações do @pbaesse e do @corvolino (esta em partes) e de outra pessoa que não recordo no telegram, e estou adicionando pessoas no [subgrupo do loomio](https://gti.partidopirata.xyz/loomio).

Pseudo link: `gti.partidopirata.xyz/loomio`

Link canônico: https://www.loomio.org/g/JDmI4ZKv/

**Comment by desci** [comment]
Ah, também cabe esclarecer que o @mtoledo62 me enviou a lista de e-mails das pessoas que se inscreveram no [formulário](http://partidopirata.org/chamada-aberta-para-os-grupos-de-trabalho/) para integrarem o GTI. Vou adicionando oportunamente estes endereços, adianto que um deles é um endereço expirado ou inválido.
