### ISSUE TITLE
Reativar wiki

### ISSUE THREAD

**Issue by desci** [piratas/gti#19]
A mediawiki que havia em **wiki.partidopirata.org** não está bem configurada no `suecia1` e os arquivos de configuração do site da anapirata, do de transparência e da wiki foram expostos publicamente porque o disco do `suecia1` estava cheio e o php e o apache com problemas.

Já estou com o backup da mediawiki, mas proponho que utilizemos a ikiwiki no lugar da mediawiki.

Ikiwiki usa git como banco de dados e eu tenho um exemplo no ar em <https://partidopirata.xyz>, também acessível em <https://piratas.xyz>.

O repositório é atualizado por um hook do git a toda alteração da wiki (que é um commit) em três repositórios remotos: no [notabug](https://notabug.org/piratas/partidopirata.xyz), no [gitlab](https://gitlab.com/piratas/partidopirata.xyz) e aqui no [github](https://github.com/piratas/partidopirata.xyz). É possível editar a wiki clonando ela e enviando git push!

Para a maioria das pessoas, há também uma interface web onde é possível editar páginas em markdown (igual na mediawiki). A ikiwiki já tem openid nativo.

Ikiwiki roda em perl e consome muito pouco do servidor, é possível utilizá-la como blog e eu estou ativamente [melhorando o frontend](https://iikb.org/tarefas) e [escrevendo plugins](https://ikiwiki.info/users/desci/).

Atualmente um pirata insurgente criou um espaço para o partido na [wikiversity](https://pt.wikiversity.org/wiki/Portal:Piratas), e eu criei esta wiki "piratas.xyz" no servidor `entwickler`.

**Comment by desci** [comment]
Ah, esqueci de dizer que nesta ikiwiki eu estou propondo criar um [blog](https://piratas.xyz/blog), um [issue tracker](https://piratas.xyz/tarefas), um [feed de reuniões](https://piratas.xyz/reuniões) com espaço para relatoria, além de um [forum](https://piratas.xyz/forum), tudo isto integrado com a wiki propriamente dita, afinal, usa sempre a mesma plataforma.

Ressalto que o banco de dados está redundante em três repositórios git e em caso de queda do servidor pode ressurgir em segundos.

**Comment by iannsp** [comment]
pelo jeito da pra centralizar bastante coisa no ikiwiki e ficar mais facil de dar manutenção, correto?
eu acho uma atitude positiva bagarai.

**Comment by iannsp** [comment]
[a wiki esta sendo reativada](https://piratas.xyz)
podemos fechar essa tarefa aqui?

**Comment by desci** [comment]
@iannsp na verdade a proposta é mover **piratas.xyz** para **wiki.partidopirata.org**, ou seja, oficializar a ikiwiki como ferrementa oficial. Depois de polir bem, claro.

**Comment by pbaesse** [comment]
Muito interessante a proposta. Só uma dúvida, o forum ficaria exatamente como?? Me preocupo com a usabilidade dele na verdade.

**Comment by desci** [comment]
@pbaesse que nem uma página de discussão da wikipedia, com a adição do plugin de comentários da ikiwiki que tu pode ir lá e testar tu mesmo

**Comment by desci** [comment]
@desci entretanto eu não recomendo para substituição de uma ferramenta de forum propriamente dita, aquilo está lá pelo motivo de que todo e qualquer espaço nosso vira um forum de qualquer forma.

**Comment by pbaesse** [comment]
Ah tá. Já pensou no uso do Discourse para o fórum??

**Comment by desci** [comment]
Estou apontando o domínio pra lá mas seria interessante fazer o tutorial de como usar a ikiwiki conforme <https://piratas.xyz/tarefa/__91__wiki__93___Tutorial/>

**Comment by desci** [comment]
@pbaesse o coletivo mineiro usa discouse: <http://partidopiratamg.org/>

**Comment by desci** [comment]
Wiki agora está em https://wiki.partidopirata.org (sim, com SSL!). O software utilizado é [ikiwiki](https://ikiwiki.info), portanto TODAS alterações na wiki são commits e são sincronizados de 10 em 10 minutos em três repositórios remotos, como é o caso do <https://github.com/piratas/wiki-piratas>.

Ou seja, qualquer pessoa pode "baixar" a wiki inteira, incluindo o histórico de alterações, páginas removidas e etc. retroativamente desde o dia em que eu botei no ar. E se o servidor onde ela está hospedada cair, é o trabalho de instalar ikiwiki de novo e dar um clone no repositório.

Alias, como a ikiwiki usa markdown, com a exceção das diretivas específicas da ikiwiki, é possível visualizar diretamente aqui no github a própria wiki, caso alguém esteja atrás de um firewall que não abra partidopirata.org e abra github.com (meus pêsames).
