### ISSUE TITLE
Centralização do fluxo de trabalho do GTI

### ISSUE THREAD

**Issue by desci** [piratas/gti#23]
> Como assim? Github não serve?

Não é isto. Vou tentar explicar em palavras:

Várias vezes a gente tentou definir e decidir um meio de centralizar e um fluxo de informações. Alguns funcionaram bem para organização interna do GTI e mal para as pessoas que precisaram do GTI, outros funcionaram bem para uns e nem tão bem para outros.

Atualmente tem um monte de tarefas no [notabug](https://gti.partidopirata.org/notabug) e tem gente que ainda usa lá. Tem também o [taiga](https://gti.partidopirata.org/taiga) que recebe todas as atualizações aqui do github, assim como o telegram e a wiki também recebem.

Se a gente tivesse o nosso próprio gitlab ou gogs, isto eliminaria a necessidade de usar o github e o notabug. No entanto a maioria das pessoas costuma argumentar em favor de não usar ferramentas próprias (me corrijam).

Isto está sendo discutido no loomio [aqui](https://www.loomio.org/d/NEu5z1oI/escolher-uma-ferramenta-principal-para-organizar-as-tarefas-gti) e [aqui](https://www.loomio.org/d/1BdUTneg/centralizar-tarefas-na-wiki-http-piratas-xyz-), e eu gostaria que mais gente participasse.

**Comment by desci** [comment]
Vou remover os links para a wiki (redundante), para o Taiga e o Notabug do site do GTI, por falta de uso destes recursos.

Isto efetivamente tornará o site enxuto, e direto ao ponto no sentido de dizer para as pessoas: escolha um de três: deliberações e decisões (loomio), tarefas e trabalho (github), chat e discussão (telegram).

Eu sinceramente preferia de outro jeito. Vou continuar tentando interagir com as pessoas no taiga e no notabug sempre que possível e dar menos atenção para o telegram (que mais come tempo do que produz realmente).

**Comment by pbaesse** [comment]
Mas algumas conversas poderiam/deveriam migrar do Telegram para o github já
que o controle de tarefas é por aqui.

Abs,
Baesse
Professor Sistemas de Informações
Especialista e Mestrando em Gerenciamento de Projetos
contato.pbaesse.net
+55 84 9184-6494

2016-06-14 0:42 GMT-03:00 Desobediente Civil <notifications@github.com>:

**Comment by fredguth** [comment]
Sou novato e posso dar um relato da perspectiva de quem está chegando:
Está tudo muito confuso.

É muito meio de comunicação, ferramenta, etc.
É melhor criar algumas convenções.

**Comment by desci** [comment]
Nova votação no Loomio:

Manter o Github como ferramenta principal

Enquanto não temos nosso próprio gogs ou gitlab, manter centralizado em https://github.com/piratas/gti todas as tarefas, sendo o loomio para deliberações. Prazo indefinido.

https://www.loomio.org/d/NEu5z1oI/proposal/GzgUjq18

**Comment by pbaesse** [comment]
Nice! You've received an invite from Pedro to create a bot!

Yay! I just made my personal bot. It's like my digital twin who knows about me and can respond to all messages and queries on my behalf automatically.

It’s a cool way to build a smart universal identity on the web.

Go ahead, create your own bot now ➜ https://u2119513.ct.sendgrid.net/wf/click?upn=BKWcjsYYEnbyb53avBNV6R9cEHvnpwBQa6bkDe0g1p0qBo2wu6luStR1z4xCMGuQbaWjUbKjWg-2FPa-2F5xi-2B3gXQ2JBCrqsio9L3QZr2rnzjArAErmw3TKvRuSStbS8HSl_s5UH8bhnBaopYjthcNSRcQv8ZiN28GEB5iuzPfUzoQ0iE-2B9iX-2Bfh3XGytkeMUvY-2BzxYH57p-2BGKFw0DdwQ0Xyjpfoqx-2BhKHD9Irr7tdM1MkB9SZaNu6DnC4-2FcYNgGL47W0znoSiU6Y-2B7ScvbTfnK6ZPQtiKlvcg8cQaLpWgMfiG-2FLt8XgBCzI3VxtkGmlTjvoAbMiPgxSQbF-2BbG6MzxhuYth6bTAHPn8xks3SWMrLjI6k8xagzFx-2F6k7YQK48pqHDIomPv2PGkMbg21kGQcctMCqW5qUFYgXsgEjPlPZcp3dfx3bjQi55BPRisRg6S0KZacey4ReN4zw9nes-2FAX6k2qKITDuMvhv3taj-2FzCWH0dnH7S1sR08O7Xl48AwTrOvt
 Talk to us 
 https://u2119513.ct.sendgrid.net/wf/click?upn=BKWcjsYYEnbyb53avBNV6cS-2FNKrzUTW6aAcK1zezjse1PjxAEBiEIsPGuw4M8AQGeasKEqfAkKxrM1azLwQ-2Ff6uiElbF-2BASdzkwJ6xRfEMgIntAATkEO-2B8sIOayCd8Mw_s5UH8bhnBaopYjthcNSRcQv8ZiN28GEB5iuzPfUzoQ0iE-2B9iX-2Bfh3XGytkeMUvY-2BzxYH57p-2BGKFw0DdwQ0Xyjpfoqx-2BhKHD9Irr7tdM1MkB9SZaNu6DnC4-2FcYNgGL47W0znoSiU6Y-2B7ScvbTfnK6ZPQtiKlvcg8cQaLpWgMfiG-2FLt8XgBCzI3VxtkGmlTjvo8AV5o2fxkHwztPocI2Z-2FfmBf6ngNaguSG9m4Fn-2FqqQ9hR1wudKO7B62i7U41w0jXyBOxcEqnOmbYjaVf-2BTiHSKv8bQvf-2FFgoyV-2FeMue3gBgPV1-2BNLc12clbRi8l44oVZrNPl3Wk3eVawUns8Hq-2Fjb983WIvHqWvkEYuvd2U5AnHJ-2FaKvNywocbnMpu90xaIi

Visit us 
 https://u2119513.ct.sendgrid.net/wf/click?upn=BKWcjsYYEnbyb53avBNV6R9cEHvnpwBQa6bkDe0g1p0qBo2wu6luStR1z4xCMGuQbaWjUbKjWg-2FPa-2F5xi-2B3gXQ2JBCrqsio9L3QZr2rnzjArAErmw3TKvRuSStbS8HSl_s5UH8bhnBaopYjthcNSRcQv8ZiN28GEB5iuzPfUzoQ0iE-2B9iX-2Bfh3XGytkeMUvY-2BzxYH57p-2BGKFw0DdwQ0Xyjpfoqx-2BhKHD9Irr7tdM1MkB9SZaNu6DnC4-2FcYNgGL47W0znoSiU6Y-2B7ScvbTfnK6ZPQtiKlvcg8cQaLpWgMfiG-2FLt8XgBCzI3VxtkGmlTjvo1RugmXNKxzkRVvUAkX8QB-2Bv24Y89PGSw-2BodQtU2318VikQTJHUy1MihuAGl4j64jWs-2BF1f41JZePU9l95cTVTxH8glHZwphOqbMmkmzAVn76Ff7CeD8RLggLbH8bQOu4GW7-2B-2Bx-2B9oocAgEmLxAyY8GihBOXdoNb0inm5M5hRn0BUbR5YIRDdFMsG8-2FX4xW4E

340 S Lemon Ave, Walnut, CA, 91789 

© HELP Inc. 2017 

Unsubscribe https://u2119513.ct.sendgrid.net/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcQv8ZiN28GEB5iuzPfUzoQ0iE-2B9iX-2Bfh3XGytkeMUvY-2BzxYH57p-2BGKFw0DdwQ0Xyjpfoqx-2BhKHD9Irr7tdM1MkB9SZaNu6DnC4-2FcYNgGL47W0znoSiU6Y-2B7ScvbTfnK6ZPQtiKlvcg8cQaLpWgMfiG-2FLt8XgBCzI3VxtkGmlTjvokvtF43iUMBncrIwEmJeZ2woAAGmPRcrer5NHAVqBvij9DVHyw9Kw0utxE2hiyblOeHCEHiTPj7xMeHf6MleGErGRYiZJkMfDEl8scEJeE4IYXUFGcGnCUILz7-2FpAaSIooW8YRWW5u9Rs4PHQBUhj8b9YlXLexNI1tQayqvSE2Hkw-2Fhyr3cdlQGpDQjUOBZfN, we hate goodbyes :(

**Comment by iuriguilherme** [comment]
Tchê @pbaesse , essa merda foi pro e-mail de todo mundo, pro telegram, pro irc e pra matrix
