### ISSUE TITLE
Próxima Reunião

### ISSUE THREAD

**Issue by pbaesse** [piratas/gti#24]
Estamos precisando de uma reunião para organizar os rumos do GTI. É nessa quinta reunião??

**Comment by iannsp** [comment]
gostaria de comparecer a esta reunião.
Onde? quando? pauta?

**Comment by desci** [comment]
**Era** quarta feira dia 25.

Adiamos por reivindicação de uma pessoa (a que sugeriu que fosse dia 25) no mesmo dia.

Sugiro definir um dia mais tardar até sexta feira dia 3 de junho.

**Comment by iannsp** [comment]
@desci , estranho, eu não vi nenhuma comunicação sobre essa reunião.
por favor, me diga quando da nova data para que eu possa participar.
obrigado.

**Comment by desci** [comment]
O único canal de anúncios em uso é o do [telegram](https://telegram.me/joinchat/ApLxJjzfzV5YTnTHO10GCQ)

**Comment by corvolino** [comment]
1 de Junho de 2016 às 22:00h terá uma reunião do GTI.

**Comment by iannsp** [comment]
@corvolino mumble?

**Comment by pbaesse** [comment]
O canal de anuncio poderia ser aqui e no loomio.

Houve reunião ontem??

**Comment by desci** [comment]
A reunião foi dia 8 de junho e a relatoria está aqui: <https://wiki.partidopirata.org/reuniao/Quarta_reuni%C3%A3o_do_GTI_em_2016/>
