### ISSUE TITLE
Sistema de transparência financeira

### ISSUE THREAD

**Issue by desci** [piratas/gti#28]
Conforme discutido no telegram (aquela porcaria), chegou a hora do GTI assumir o desenvolvimento de um sistema de transparência financeiro a ser utilizado pela tesouraria nacional, e possivelmente pelas demais tesourarias.

Os requisitos básicos são:

* Registrar as entradas e saídas de dinheiro;
* Providenciar uma interface que não técnicos podem utilizar para alimentar o sistema;
* Integração com sistemas como por exemplo, mas não limitado a: internet banking, blockchains e sites de pagamentos;
* Apresentar dados de forma compreensível para pessoas sem conhecimento avançado em finanças;

As demais pessoas que já tomaram a iniciativa de criar um sistema de transparência financeira deram algumas ideias durante o caminho, que estão perdidas por aí. O mais importante é começar a fazer, pra gente ir se organizando conforme o trabalho que realizamos.

O sistema de transparência financeira em uso atualmente está descrito na [wiki](https://wiki.partidopirata.org/wiki/tesouraria), a grosso modo consiste na publicação de links para planilhas de google drive em tópicos de um grupo no loomio.

**Comment by pphcarv** [comment]
Ahoy,
Dando uma olhada na prestação de contas do ano 2015, parece que os gastos não são tão altos, daí não deve ainda ser muito complexo. Não rola de, ainda que temporariamente, fazermos esse controle/publicidade por meio de uma planilha do Google Docs? Resolve o problema de praticidade e de facilidade principalmente para não leigos.

**Comment by desci** [comment]
@pphcarv Isto já é feito. Como eu informei no telegram, o sistema atual de transparência financeira consiste em lançar informações em planilhas do google docs e publicar no [loomio](https://www.loomio.org/g/Tvhxj2Bq/tesouro-pirata).

Vou tentar garimpar a informação e trazer aqui para esta issue no github.

**Comment by fredguth** [comment]
@desci 

É possível usar o ledge (http://ledger-cli.org/) como _core_ e ter uma interface web para input de dados.  A grande vantagem do ledge é que tudo é armazenado em arquivo texto, ou seja, daqui 40 anos será possível acessar e ler os dados.

Depende bastante de quanto esforço quer se investir nisso.  Uma outra solução bem mais simples de implementar é usar o FieldBook.  Não é livre, mas é grátis. Eu uso para várias coisas pessoais e até meus pais conseguiram usar... é tipo um Access na web.

**Comment by desci** [comment]
Tópico criado no Loomio: https://www.loomio.org/d/yHs4JC6n

**Comment by desci** [comment]
Referenciando 84692962037b309b960e3d8ba99627684784b4d2

**Comment by desci** [comment]
Pendências:

- [ ] Consertar minha cagada e esclarecer no tópico loomio que este projeto deveria cer centralizado aqui na issue 28 do github;
- [ ] Fazer o que eu prometi que ia fazer e documentar o atual sistema de transparência financeira do partido;
- [ ] Lembrar os tesoureiros que este processo está se dando por aqui;

**Comment by fredguth** [comment]
Jóia, vou trazer para cá todos os documentos que estão referenciados no Loomio

**Comment by fredguth** [comment]
##Lista de comandos:

```$ hledger -h
hledger [COMMAND] ... [OPTIONS] [ARGS]

Data entry commands:
  add              prompt for transactions and add them to the journal

Reporting commands:
  print            show transaction entries
  accounts         show account names
  balance          show accounts and balances (bal)
  register         show postings and running total (reg)
  incomestatement  show an income statement (is)
  balancesheet     show a balance sheet (bs)
  cashflow         show a cashflow statement (cf)
  activity         show an ascii barchart of posting counts per interval
                   (default: daily)
  stats            show some journal statistics

Add-on commands:
  api
```
###Para entender os comandos
http://hledger.org/step-by-step.html#basic-data-entry-reporting

**Comment by fredguth** [comment]
Referências:
https://github.com/conservancy/npo-ledger-cli
http://fava.pythonanywhere.com/example-2-beancount-fava-0-3-0-2016-07-27-pypi/income_statement/
http://www.justicaeleitoral.jus.br/arquivos/tse-resolucao-n-23-464-2015-contabilidade-dos-partidos
http://www.tse.jus.br/partidos/contas-partidarias/prestacao-de-contas-partidarias/modelo-das-prestacoes-de-contas-exercicio-financeiro-de-2015

**Comment by webarthur** [comment]
Cai aqui pelo odiável feed do Loomio via email... rápido e direto: tem algo eu possa ajuda aq Desci? (tão usando até gulp, que moderno)

**Comment by fredguth** [comment]
@webarthur Sim.  Pode me procurar no Telegram (@fredguth)
Você entende de integração contínua?
precisamos de alguém que ajude a rodar o ledger e não permitir mergear se não estiver ok.

**Comment by desci** [comment]
Time novo nesta organização do github: @piratas/tesouro 

Repositório novo nesta organização do github: https://github.com/piratas/tesouro-pirata

Quem quiser somar esforços, avise nesta issue ou de outra forma para ser adicionada(o) ao time @piratas/tesouro

**Comment by desci** [comment]
Para facilitar a organização, sugiro utilizar o [issue tracker pertinente](https://github.com/piratas/tesouro-pirata/issues) recém criado.

Sois vós.
