### ISSUE TITLE
Autenticação site partidopirata.org

### ISSUE THREAD

**Issue by desci** [piratas/gti#42]
*Enviado por e-mail*

---

Olá Membros do Grupo de TI do Partido Pirata.

Peço gentilmente que quem tenha acesso a diretório de instalação do site wordpress partidopirata.org favor apagar o plugin de limite de tentativas de login (limit-login-attempts) possivelmente dentro de /wp-content/plugins/ o quanto antes possível

**Comment by gomex** [comment]
Vale a pena ressaltar que ele deseja remover o plugin apenas para que ele possa acessar a interface administrativa... a ideia é configurar corretamente o plugin...

**Comment by desci** [comment]
@gomex sim, não ta claro, nem subjetivamente qual é o problema, e nem porque é que tem que apagar isto.

Além disto, não sei quem instalou essa coisa nem o que vai acontecer quando apagar - ele não ta na [lista de plugins](https://github.com/piratas/piratas-site/tree/master/plugins), então tem que pegar o que ta lá em produção, clonar num ambiente de teste e ver o que acontece.

---

# Referências

* <https://wordpress.org/plugins/limit-login-attempts/>
* <https://plugins.svn.wordpress.org/limit-login-attempts/>

**Comment by desci** [comment]
*Enviado para o telegram*

---

> já temos mais de 24 horas com um plugin mal configurando impedindo o acesso dos administradores da página

> De alguma forma, inexplicável, uma blocklist com um range absurdo de IPs foi configurada em um plugin do wordpress para impedir erros de login.

**Comment by mtoledo62** [comment]
@gomex  quando tenta acessar o painel administrativo aparece isso:
![access](https://cloud.githubusercontent.com/assets/23246730/19984838/3c02d47a-a1f7-11e6-8262-ff538e2dbcac.jpg)

**Comment by desci** [comment]
Com as pessoas não explicando qual é o problema ja é difícil tentar solucionar, pior ainda foi tentar descobrir o que é que aconteceu e ao invés de esclarecerem, ficaram me destratando e me cobrando a responsabilidade disto.

Pior ainda é que eu to agora manualmente vendo o que fizeram e é uma cagada totalmente não relacionada com o que foi relatado. Perdi tempo tentando fazer o que pediram, e o problema é outro.

Não tinha outra hora melhor pra ficar brincando de instalar plugin no servidor de produção, tchê?

**Comment by desci** [comment]
Diretório `rename-wp-loginphp-to-anything-you-want` movido, consequentemente desativando o plugin.

Configuração de login deve ter voltado ao padrão.

Esclarecendo que o plugin *limit-login-attempts* não estava no diretório de plugins, sendo que o que realmente estava causando problemas era este:

* <https://wordpress.org/plugins/rename-wp-loginphp-to-anything-you-want/>

**Comment by desci** [comment]
Reitero que não recomendo instalar plugins no site de produção, estamos utilizando docker de forma organizada aqui no github, e o fluxo proposto é testar novas ideias e propostas em ambientes de teste e desenvolvimento e apresentar pro coletivo de forma organizada: <https://github.com/piratas/piratas-site> @piratas/docker @piratas/wordpress 

As pessoas que têm acesso administrativo deveriam ter responsabilidade pelo site do partido, ainda mais visto que neste momento pré assembleia nacional este tipo de problema não poderia acontecer.

**Comment by kannonsan** [comment]
Via painel administrativo mostram-se apenas dois plugins ativos:
Akismet
Gmail SMTP

O plugin "rename-wp-loginphp-to-anything-you-want" possui, além do que seu nome indica, um sistema anti "brute force" que limita a quantidade de tentativas de login. Uma variação do "limit-login-attempts."

Ele indica no momento que o endereço identificado por ele como do servidor do próprio wordpress "172.19.0.3" fez inúmeras tentativas de login.
Quanto a "blacklist" ela permanece vazia -- não tendo acesso aos logs não posso afirmar mais.

Questão: quem ou o que está se conectando ao site do wordpress via, ao que ele supõe, o servidor?

Docker?

![salvo servidor](https://cloud.githubusercontent.com/assets/19435297/19992459/15790698-a225-11e6-8f07-7bd3e035a6d5.jpg)

**Comment by desci** [comment]
@kannonsan isto é irrelevante para o assunto. Os comentários de problemas/tarefas do github devem servir para debate em torno da questão que está descrita na publicação de abertura.

Aqui não é um espaço pra tirar dúvidas nem ter perguntas respondidas, é pra cada pessoa dar sua contribuição, opinião ou visão acerca de determinada decisão. Ou documentar a resolução de um problema. Podemos inventar novos usos, mas este que eu descrevi certamente não está de acordo com a natureza da ferramenta.

Tu pode ir no grupo de telegram do GTI e perguntar as coisas que tu não entende e ver se alguém responde, se interessa ou cria debate em torno disto.
