### ISSUE TITLE
speakout plugin - limite para entrada de emails #3 

### ISSUE THREAD

**Issue by kannonsan** [piratas/gti#47]
este plugin para petições está instalado no servidor
entretanto ele foi instalado com limites para o campo de emails, um limite de 300 caracteres
por mais que façamos a mudança pelo administrador do WordPress, o DB continua com 300
assim diz instalador dele:
$sql_create_tables = "
CREATE TABLE $db_petitions (
		`target_email` **VARCHAR(300)** CHARACTER SET utf8 NOT NULL,
Desta forma, com o limite de 300 caracteres, não conseguimos inserir os emails de todos deputados.
Precisamos modificar esse limite.

**Comment by desci** [comment]
O procedimento padrão é reinstalar o plugin com as configurações corretas, visto que é na hora da instalação que se cria as tabelas.

Da pra alterar as tabelas com o banco de dados rodando, mas é uma péssima prática.

**Comment by desci** [comment]
Sendo tratado no repositório pertinente: https://github.com/piratas/piratas-site/issues/3
