### ISSUE TITLE
site fora do ar

### ISSUE THREAD

**Issue by mtoledo62** [piratas/gti#48]
Site partidopirata.org está fora do ar desde (pelo menos) hoje, 27/11, pela manhã.

**Comment by desci** [comment]
Obrigado pelo aviso, desculpe a demora e reforço que precisamos tornar os serviços redundantes e distribuídos pra mitigar esses downtimes - acertei nos termos técnicos?

Ver issue #14

**Comment by desci** [comment]
Em tempo: a issue atualizada é a #39
