### ISSUE TITLE
Instalar wordpress para tesouraria

### ISSUE THREAD

**Issue by fatequinha** [piratas/gti#49]
oi GTI, tudo bem?

alguem pode criar uma conta wordpress anexada com a URL tesouraria.partidopirata.org?

Eu pretendo fazer um blog onde vou fazer a prestação mensal das contas dos Piratas. Saldo Anterior, Entradas, Saídas e Saldo Final.

A principio vou fazer isso de maneira manual em posts mensais, mas depois da pra integrar isso com o futuro sistema a ser desenvolvido eventualmentequemsabeumdiaDeusoqueira 

Se puder també,, favor copiar o tema usado em gtc.partidopirata.org, que pra mim ta de bom tamanho

beijos 

Tesoureiro

**Comment by diegor2** [comment]
- [x] Criar repositório no github
- [x] Criar arquivo docker-compose.yml com instalação do wordpress
- [ ] Incluir o tema do gtc.partidopirata.org
- [ ] Incluir no script que replica os gits para o entwickler
- [ ] Criar tesouraria.partidopirata.org no [nginx](https://github.com/piratas/nginx.d)
- [ ] Criar serviço docker no [system.d](https://github.com/piratas/systemd.d/)

**Comment by diegor2** [comment]
@fatequinha Esse sistema é a blockchain pirata @WilsonLC ?

**Comment by fatequinha** [comment]
Não, é apenas um sistema de prestação de contas, tipo um banco de dados

O "Blockchain Pirata" ou Pirata Coin é uma fase 2 e depende de desenvolvermos um lastro mínimo, que por suadepende de conseguirmos desenvolver um estoque razoável e consistente pra loja

**Comment by diegor2** [comment]
@fatequinha Pelo que encontrei nos [historicos do github](https://github.com/piratas/tesouro-pirata), o sistema era algo assim http://demo.hledger.org/journal

Isso me parece uma forma melhor de transparência que o wordpress já que expões os valores em um formato padronizado, bem definido e em formato texto. 

Existem orgãos públicos que dizem ter dados abertos mais disponibilizam arquivos binários ou proprietários (pdf, xls, doc) ou mesmo em formatos abertos (ex: odx) porém mal-estruturados, dificultando a auditoria ou mineração e agregação desses dados para análises. Ifonte:http://brasil.io/)

**Comment by diegor2** [comment]
Port em python do ledger com interface web: https://beancount.github.io/fava/
Outras linguagens: https://github.com/ledger/ledger/wiki/Ports

**Comment by diegor2** [comment]
Aguardando #51

**Comment by desci** [comment]
Eu tinha esquecido desta, botei somente `iniciativa.partidopirata.org` na lista de certificados novos.

Se nao tiver como, tem que esperar os sete dias.

**Comment by carloscosta** [comment]
Senhores, a intenção é seguir de beancount. Customizado para as nossas necessidades, evidentemente. 

Site final será https://tesouraria.partidopirata.org/ (ainda sem certificado HTTPS válido).

O @diegor2 deu fork no repositorio do fava que é a interface Web do beancount https://github.com/piratas/fava e contratou um host para servir a aplicação. O @fatequinha vai estudar o formato do beacount http://furius.ca/beancount/#documentation

Tem uma confusão grande sobre qual repositório, se https://github.com/piratas/tesouro-pirata ou https://github.com/piratas/site-tesouraria (não existia). Eu criei o site-tesouraria e vou iniciar arquivos de configuração de deployment lá. É preciso preparar para rodar o uWSGI se não ele não aguenta a carga.

Dando close nessa pois não será em wordpress, mas vou migrar o necessário de informações daqui pra issues lá
