### ISSUE TITLE
Eleição de Representante

### ISSUE THREAD

**Issue by dseeker** [piratas/gti#5]
Nao é possivel que nem aqui dentro do GTI voces nao consigam pensar em uma forma de organização horizontal que nao necessite de uma posição fixa de representante.
Acredito que se nem o GTI consegue se auto-organizar e distribuir as tarefas num commons de interessados é praticamente impossivel que o Partido Pirata como entidade um dia consiga funcionar da unica forma que traz sentido a sua existencia.
Voces tao satisfeitos em ficar apenas replicando formas falidas de gestão ao inves de experimentar e inovar?

**Comment by lfamorim** [comment]
@dseeker Eu concordo contigo, por isso o personagem que representa o GTI é meramente alegórico. Isso devido a normas internas do partido.

**Comment by wagnerpyter** [comment]
existe uma obrigação 'estatuaria' de ter o articulador nos GTs. agora, o regimento que tentaremos manter nessa 'ideologia' aí descrita, ou seja, regra 0 : autoorganização

**Comment by dseeker** [comment]
nao há como ter as 2 regras simultâneas. se há a figura de um representante a dinâmica do processo puxa para a centralização em figuras responsáveis. o regimento para GT's somos nós do partido que criamos, nao é uma exigencia do TSE (como no caso da quebra do partido por regiões geograficas que minou grande parte da visão original do partido de redesenhar as relações geopoliticas) e pode ser alterado se levado ao coletivo com as modificações que achamos necessárias.

**Comment by pbaesse** [comment]
Mas e até vamos ficar parados??

**Comment by desci** [comment]
@dseeker 
> Nao é possivel que nem aqui dentro do GTI voces nao consigam pensar em uma forma de organização horizontal que nao necessite de uma posição fixa de representante.

Quem aqui está tentando elencar representantes?

@dseeker
> e pode ser alterado se levado ao coletivo com as modificações que achamos necessárias.

Claro que sim, e o que é que isto tem a ver com a reconstituição do GTI com o estatuto **na forma em que se encontra**?

O fato das pessoas considerarem o atual estatuto como válido e legítimo (abaixo de protestos, que tu não viu porque não foi na reunião),não significa necessariamente que está todo mundo plenamente satisfeito com o mesmo, e que não há vontade de mudar.

O estatuto é engessado no sentido de que é necessária a assembleia nacional para alterá-lo, e o processo de retomada do GTI está atrasado desde 2014, é urgente.

Esta discussão é necessária e pertinente, o que é impertinente é associar a tolerância a um estatuto incorreto à submissão das pessoas aqui presentes a um sistema vertical de mesmice que obviamente não é a intenção de ninguém.

**Comment by dseeker** [comment]
@desci aqui
https://github.com/piratas/gti/blob/master/README.md#eleição-do-articulador

**Comment by desci** [comment]
@dseeker o texto obviamente ta errado, não era mais fácil ir lá e consertar?

Tudo bem, tu perguntou antes. Mas tu veio com pedras na mão e recebeu a resposta que esta atitude merecia.

Pode editar aquela parte de texto e dar push diretamente, realmente essa coisa de "representar" foi um erro de quem lançou o arquivo originalmente.

**Comment by dseeker** [comment]
O texto nao esta "obviamente errado", ele demonstra um entendimento e uma intenção de quem escreveu, que tambem pode ser apenas documentação do que tenha sido discutido por outras pessoas.
Nao fui ali corrigir exatamente pq nao estava na ultima reuniao e vim aqui tentar entender o status da bagaça perguntando para os outros membros antes de qualquer coisa. Haverá ou não essa eleição de representante?

E na boa @desci , voce é o ultimo que pode reclamar de "pedras na mão", minha provocação é totalmente pertinente aos rumos do processo e ao entendimento das pessoas sobre objetivos do movimento pirata.  Ao contrario do tanto de bile reacionária e ataques pessoais que saem do seu teclado sem motivo ou objetivo algum.

**Comment by wagnerpyter** [comment]
pessoa escolheu o 'github' como criterio de 'eliminação', mas defendo ter uma ferramenta externa como o formulario, pq ninguem é obrigado a criar contas.

**Comment by dseeker** [comment]
@wagnerpyter discordo muito. tem milhoes de contas que os piratas tem que ter pra estar em dia com os assuntos, no telegram, slack, trello, facebook, loomio etc etc. nosso foco é estudar, discutir, propor, testar tecnologia da informação, se a pessoa que se cadastrar nao estiver nem um pouco afim de aprender e dominar estas formas de colaboração e trabalho conjunto devemos restringir a entrada sim. senao qual o proposito de um processo de seleção? 

lembrado que o partido é fundado sobre discussões em torno da tecnologia alterando nossas relações sociais, portanto discussões deste tipo sao para nós de carater politico e devem ser abordadas por todos os membros do partido, simpatizantes e curiosos, o objetivo do GTI é mais aprofundado assim como o GTJ tem um foco especializado tambem. 

qualquer pessoa minimamente interessada em colaborar com projetos open source vai ter tido ou querer ter, em algum ponto, uma conta do Github para contribuir com outros projetos. discussões sobre praticas das empresas destas ferramentas sao paralelas a nosso trabalho dentro delas e nao podem nos limitar. entendo se a questão é de integração, de se perder num mar de logins, mas se a base deste argumento for uma atitude vegana de nao consumir nenhum kilobyte de empresas do lado contrario das nossas bandeiras parece não condizer com um interesse em estudar a questão.

"ninguém é obrigado a criar contas" nem obrigado a se juntar a nenhum GT que isso seja requerimento para trabalhar

**Comment by desci** [comment]
É a minha opinião mas também foi consenso na reunião:

Ninguém tem que ser obrigado a fazer conta no github (serviço comercial e de código fechado) pra participar do GTI. O GTC erra em obrigar as pessoas a terem conta no Trello e não existe motivo pra replicar o mesmo erro.

É razoável forçar as pessoas a terem conta no github como forma de critério de eliminação pra responder cargo efetivo, de articulador ou similar no GTI. Não é o ideal, porque já evoluímos nisto e as pessoas concordaram no passado que o Gitlab é melhor que o Github para o nosso caso, mas é um meio termo razoável por enquanto.

Não definimos processo de seleção na reunião, isto é necessário? Se sim, deveríamos elencar logo qual será o meio principal de comunicação, seja github, lista de e-mail ou loomio, ou tentar de novo com telegram, mas eu pessoalmente acredito que isto deve ser feito em uma reunião com relatório e etc., até porque não fizemos a segunda reunião que devia ter sido feita.

**Comment by desci** [comment]
Ah, e assim como Telegram não funcionou, Github pra mim obviamente não funcionou também.

Precisamos de uma ferramenta que seja superior à nossa mania imbecil de criar um tópico pra falar de qualquer coisa menos o assunto do tópico, como acontece aqui.

Se não tem ferramenta, então código de conduta é necessário, mas confiar no bom senso dessa galera ta cada vez mais duvidoso

**Comment by lfamorim** [comment]
O assunto será discutido na reunião de domingo, como é uma questão de opinião e aqui não suporta votação, mas edição e aprimoramento, estou fechando a thread.

**Comment by desci** [comment]
Não teve reunião domingo.

**Comment by desci** [comment]
Registro que assumi a articulação e estou (na velocidade máxima que eu consigo) propondo e implementando meios de horizontalizar e inovar, dentro dos meus limites.

**Comment by iannsp** [comment]
@desci vc não assumiu a articulação, você sequestrou.
Velocidade maxima sem controle é acidente com morte na certa! Precisamos organizar e executar, de maneira organizada e focada nos objetivos do partido(mais focados nisso do que agora).

**Comment by lfamorim** [comment]
@iannsp Como assim? Eu não concordo com essa sua afirmação. Explique.

**Comment by iannsp** [comment]
@lfamorim qual parte dela?
Sobre o sequestro? O @desci esta trabalho? ESTA! O @desci esta ajudando? ESTA! 
As pessoas sabem o que esta sendo feito? Nao!
Eu posso ajudar? Não? Por que todo lugar que todo tem um lock que me impede de trabalhar pq esta orientado as decisões tomadas pelo @desci(que esta fazendo isso pq acredita que não tem apoio, sozinho).
Eu demorei um mês tentando ter acesso a uma lista de trabalho que fosse informativa ao inves de ruido. E o @desci centralizou aqui no github, finalmente. Espero que o proximo passo seja na reunião dessa quinta-feira alinhar as coisas que precisam ser feitas para que eu possa requisitar acesso e executar o que precisar ser feito.

Se sua duvida for sobre o que disse de executar com velocidade, bem. Tira o freio do seu carro e a direção, e acelera ele.

**Comment by lfamorim** [comment]
@iannsp Mas isso não significa que ele tenha sequestrado, ficou decidido que ele seria o articulador de forma bem estruturada. não é golpe ou sequestro, seria se ele fosse deposto.

Quanto a organização, eu tenho uma empresa de tecnologia, acredito que o problema seja outro, mais relacionado com o ciclo de um projeto do que qualquer outra coisa. Minha crítica é, tenho visto muita gente trabalhar e pouca gente aproveitar o que foi feito ao custo de madrugadas. O Partido Pirata tem um potencial imenso, precisamos apenas nos organizar. Nessa quinta o faremos.

Abs.

**Comment by iannsp** [comment]
@lfamorim hahaha
não disse que é golpe. hahahaha
O @desci  não é do mal, de jeito algum!
Sobre ter uma empresa de tecnologia, otimo! Eu não tenho uma.
Sua critica de "pouca gente aproveitar", eu diria que corrobora com minha afirmação. De que se não estiver organizado não ganha tração, não tem objetivo, não alinha com objetivos táticos nem estratégicos, mas ó... da um trabalho danado.
