### ISSUE TITLE
Certificados da Let's Encrypt

### ISSUE THREAD

**Issue by desci** [piratas/gti#51]
*Se a pergunta não se aplicar, deixe sem resposta*

### A que site, ferramenta ou coisa esta questão está relacionada?

    certificados ssl para todos domínios

---

### Descreva a ideia, projeto, sugestão, use quantas palavras quiser ou precisar:

    não sei

### Quem vai ser responsável por organizar?

    não sei

---

### O que tu tentou fazer?

    renovar os certificados para todos domínios que estão hospedados no servidor entwickler

### O que deveria acontecer?

    o certbot renovar todos domínios por mais três meses

### O que aconteceu?

    There were too many requests of a given type :: Error creating new authz :: Too many currently pending authorizations.

### Como reproduzir o problema?

    sudo systemctl -l stop nginx.service; sudo certbot renew; sudo systemctl -l start nginx.service

**Comment by diegor2** [comment]
@desci Eu tive uma ideia:

**Comment by desci** [comment]
O certbot somente permite que se altere a conta quando ele nao detecta outro arquivo de conta no direto'rio de trabalho.

Ou seja, a u'nica forma de mudar a conta e' movendo o direto'rio `/etc/letsencrypt` e comecando de novo - gerar os certificados novamente, na primeira vez sera' necessa'rio providenciar um e-mail (usar outro) e aceitar os termos novamente. Nao importa se as opcoes `--agreee-tos` ou `--email` forem providenciadas, aparentemente.
