### ISSUE TITLE
Allows POEditor to read and commit language files from/to your repos.

### ISSUE THREAD

**Issue by dseeker** [piratas/gti#52]
@diegor2 fomos notificados para permitir acesso deste site nos repositorios. 

![image](https://cloud.githubusercontent.com/assets/11655138/24355875/ec0ea986-12f7-11e7-9097-709f0eff7dda.png)

tem mais informações sobre a utilização disso?

**Comment by diegor2** [comment]
Estava tentando abrir o arquivo de tradução do fava num editor online. Como não tinha acesso, fiz um fork e tentei abrir a copia no meu usuário, mas também não deu certo. Acabei desistindo.

A ideia era ver se nesse editor online ficava mais facil para algum voluntário que não tivesse familiaridade com programação ajudar na tradução do sistema de transparência.

**Comment by dseeker** [comment]
ok, obrigado pelo esclarecimento, posso deletar essa autorizacao entao?

**Comment by diegor2** [comment]
sim

**Comment by desci** [comment]
@diegor2 Não sei se github tem integração com poedit, nem vou pesquisar isto. Mas se a ideia é atrair colaboradoras(es) pra esse tipo de coisa, usa transifex
