### ISSUE TITLE
Novo Servidor

### ISSUE THREAD

**Issue by mtoledo62** [piratas/gti#53]
É sabido que no final deste semestre o servidor onde atualmente se encontra hospedado o site partidopirata.org terá seu contrato encerrado e que não há interesse em renová-lo. Porem, necessitamos que o site siga em funcionamento e por isso precisaremos de um novo servidor. Sendo assim, há uma nebulosidade sobre o futuro deste problema.

O servidor contratado pelo @diegor2 na Scaleway para o Iniciativa Pirata é suficiente para abrigar as demais necessidades do partido? Se não, há algum relatório de necessidades para que possamos buscar um novo servidor que se enquadre nesses requisitos?

**Comment by desci** [comment]
@mtoledo62 a única necessidade que há documentada até hoje é manter o wordpress em partidopirata.org disponível

**Comment by desci** [comment]
@mtoledo62 de onde veio essa informação de que não há interesse em renovar o servidor onde o site atualmente está?

e que pesquisa é essa que só identificou um servidor da scaleway como alternativa?

**Comment by mtoledo62** [comment]
Você havia dito que o bombardelli iria pagar até o fim deste contrato apenas, segundo análise de um colaborador do GTI aquele servidor não está suportando receber muitos acessos. Então acredito que é o momento para que possamos buscar alternativas com melhor estrutura.

Não houve pesquisa indicando apenas scaleway como única alternativa, isso foi uma pergunta. O servidor já contratado na Scaleway é o suficiente ou precisamos buscar um novo? Se não for o suficiente, quais seriam as necessidades técnicas dos servidores para que possamos buscar?

Por exemplo:
Precisamos de servidores que:
I) Seja dedicado
II) Esteja localizado em país X, Y ou Z, em função das leis de segurança digital.
III) Tenha pelo menos XGB de armazenamento SSD
IV) Permita XGB de tráfego mensal
V) XGB de memória RAM
e etc...

Aí buscaríamos o que melhor se enquadra nas necessidades, escolhemos um e tentamos alguma forma de viabilizar o pagamento.

ps: não é uma briga, só estou preocupado com a questão do servidor mesmo

**Comment by diegor2** [comment]
@mtoledo62 entiwickler (kimsufi)
baremetal
CPU Atom N2800 (dual core) @ 1.86 GHz
RAM 4 GB
HD 1 TB
Rede 100 Mbps (ipv6)

iniciativa (scaleway)
vps (máquina virtual)
CPU Atom C2750  (dual core) @ 2.40GHz
RAM 2GB
SSD 50GB
Rede 200Mbps (ipv4)

**Comment by desci** [comment]
@mtoledo62 

> Você havia dito que o bombardelli iria pagar até o fim deste contrato apenas

Eu nunca disse isto.

> segundo análise de um colaborador do GTI aquele servidor não está suportando receber muitos acessos.

Essa análise é mal feita então, a OVH não é lider de mercado por acaso. O servidor é excelente.

> Então acredito que é o momento para que possamos buscar alternativas com melhor estrutura.

Então esclarece que é tu quem não tem interesse naquele servidor.

> Não houve pesquisa indicando apenas scaleway como única alternativa, isso foi uma pergunta. O servidor já contratado na Scaleway é o suficiente ou precisamos buscar um novo? Se não for o suficiente, quais seriam as necessidades técnicas dos servidores para que possamos buscar?

Se forem as especificações que o @diegor2, o servidor da scaleway é suficiente para colocar o site do partido, contudo desnecessário, sendo que tem outros servidores no ar com as mesmas especificações ou melhores. Mas quanto mais gente querendo ajudar, melhor.

> Por exemplo:
> Precisamos de servidores que:
> I) Seja dedicado
> II) Esteja localizado em país X, Y ou Z, em função das leis de segurança digital.
> III) Tenha pelo menos XGB de armazenamento SSD
> IV) Permita XGB de tráfego mensal
> V) XGB de memória RAM
> e etc...

Em relação a armazenamento, os uploads do site estão em 500MB e o banco de dados em 250MB. Levou cinco anos pra juntar esse tamanho.

Em relação à memória e processamento, o Wordpress sendo a merda que é consome memória desnecessariamente, então não interessa quanta memória tenha o servidor, o site vai cagar com qualquer configuração e não vai ficar melhor com mais memória. O mínimo de memória é 32MB. Qualquer VPS vai ter pelo menos 256MB e um processador de mais de 1GHz, então isto nunca será uma preocupação.

Em relação à conexão, o site é pouco acessado e não consome muito tráfego, é improvável que ultrapasse o limite normalmente imposto. Mas eu pessoalmente não gosto de serviços com limite de tráfego mensal.

Em relação a software, preferencialmente pra continuar com o esquema atual, o servidor tem que rodar docker, mas se tiver servidor web e php, é o suficiente.

Em relação à legislação, o site não tem nada de especial e nenhuma expectativa de ter conteúdo conflitante no futuro. A não ser que em algum país seja proibido botar sites de partidos ou de partidos piratas, o que eu duvido.

Se tem pelo menos mais um site (iniciativa pirata), então tem que calcular os requisitos deste também.

> Aí buscaríamos o que melhor se enquadra nas necessidades, escolhemos um e tentamos alguma forma de viabilizar o pagamento.

É o que estamos fazendo esse anos todos. É justamente porque estamos fazendo isto que este servidor está aí funcionando. Se tu quer ajudar, tu é bem vindo.

> ps: não é uma briga, só estou preocupado com a questão do servidor mesmo

Se tu estivesse lendo o que eu escrevo desde 2014 tu ia perceber que esta é a minha preocupação principal. A maioria da documentação que eu produzo é pra tentar resolver e agregar gente pra tentar resolver isto.

Se tu não gosta do servidor onde o site está ou não tem interesse nele, então ao menos respeita o interesse que as outras pessoas têm. Agora a menos que alguém tenha um plano novo, com capacidade pra provar que é uma coisa nova e que vai dar certo, estamos batendo cabeça há anos sem conseguir consenso e comunhão de esforços pra decidir a infra de TI, arrecadar dinheiro e manter as coisas. Então é chato ter uma iniciativa em andamento e ao invés das pessoas ajudarem a financiar, aparecerem para começar tudo do zero como se não tivesse nada sendo feito.

**Comment by diegor2** [comment]
@desci Se o problema é apenas quando há picos de acesso, uma cdn (cloudflare, cloudfront, etc) deve ajudar muito já que a maior parte do conteúdo é estático (um blog).
O que dá para fazer também é rodar um teste de carga para ver o quanto o servidor aguenta.

**Comment by desci** [comment]
@diegor2 A própria OVH faz testes de carga e tem lá no site deles. Inclusive os últimos grandes DDOS foram contra a OVH e o site do partido nunca saiu do ar (muito embora não estivesse na lista dos ataques).

Quem disse que tem problemas com picos de acesso?

**Comment by mtoledo62** [comment]
> Eu nunca disse isto.

já disse sim, mas enfim...

> Essa análise é mal feita então, a OVH não é lider de mercado por acaso. O servidor é excelente.

Vou pedir pra ele me passar a análise e colo aqui quando me mandar. E quanto a OVH ser líder do mercado não significa nada, a Intel tem i7 fodão e tem celeron; o plano contratado na OVH nem é vendido mais, já "saiu de linha". Mas se o servidor é tão bom deve ser coincidência então quando tem um post que viraliza o site cair.

> Se forem as especificações que o @diegor2, o servidor da scaleway é suficiente para colocar o site do partido, contudo desnecessário, sendo que tem outros servidores no ar com as mesmas especificações ou melhores. Mas quanto mais gente querendo ajudar, melhor.

Não sabia que haviam outros servidores, na wiki ( https://wiki.partidopirata.org/wiki/infra/ ) são indicados apenas o atual e o meu antigo (que em breve sai do ar, estou migrando).

> É o que estamos fazendo esse anos todos. É justamente porque estamos fazendo isto que este servidor está aí funcionando. Se tu quer ajudar, tu é bem vindo.

O que precisarem da minha ajuda e eu puder ajudar, é só falar.

>Se tu estivesse lendo o que eu escrevo desde 2014 tu ia perceber que esta é a minha preocupação principal. A maioria da documentação que eu produzo é pra tentar resolver e agregar gente pra tentar resolver isto.

Procurei na wiki, mas não achei documentação em relação a isso. Por isso fiz esse issue

>Se tu não gosta do servidor onde o site está ou não tem interesse nele, então ao menos respeita o interesse que as outras pessoas têm. Agora a menos que alguém tenha um plano novo, com capacidade pra provar que é uma coisa nova e que vai dar certo, estamos batendo cabeça há anos sem conseguir consenso e comunhão de esforços pra decidir a infra de TI, arrecadar dinheiro e manter as coisas. Então é chato ter uma iniciativa em andamento e ao invés das pessoas ajudarem a financiar, aparecerem para começar tudo do zero como se não tivesse nada sendo feito.

Respeito sim, só estou preocupado com o funcionamento. Busquei documentação sobre o assunto e não encontrei. Na wiki fala que só está pago até outubro, vim até aqui pra poder buscar informações oferecer auxílio. Mas se está tudo certo, e tudo sob controle, posso fechar o issue então. Obrigado.

**Comment by diegor2** [comment]
Inclui o servidor "iniciativa" só na página "gastos" da wiki. Não coloquei como infra pq só peguei ele para ter o desenvolvimento da iniciativa pirata. Não sei se depois vai migrar para um servidor maior, ficar junto com os demais na entwickler, continuar pra sempre nele, etc...

**Comment by desci** [comment]
Quem estiver de fato preocupado com a resiliência do site do partido ou de qualquer projeto paralelo, mande dinheiro para o @bombark, para o @diegor2, para o @guilhermebr, para o @desci, ou se aliste pra trabalhar de graça e ficar ouvindo gente inventando mentiras que nem eu to fazendo.

Se a documentação na wiki estiver uma merda, é 50% culpa minha, porque fui eu que escrevi praticamente tudo, e 50% culpa de todo mundo, porque porque é que não estão corrigindo a informação e escrevendo também.

**Comment by desci** [comment]
Eu vou esclarecer de novo aqui pra tentar deixar claro. Mesmo sabendo que é óbvio que não vai ficar claro, que vão entender errado, e depois vão dizer que eu falei o que eu não falei.

Não está tudo sob controle e não está tudo certo e não está tudo bem.

**A página da wiki do partido que documenta, detalha e explicita os gastos com TI é a seguinte: <https://wiki.partidopirata.org/wiki/gastos/>**  
**A página da wiki do partido que documenta, detalha e explicita os gastos com TI é a seguinte: <https://wiki.partidopirata.org/wiki/gastos/>**  
**A página da wiki do partido que documenta, detalha e explicita os gastos com TI é a seguinte: <https://wiki.partidopirata.org/wiki/gastos/>**  
**A página da wiki do partido que documenta, detalha e explicita os gastos com TI é a seguinte: <https://wiki.partidopirata.org/wiki/gastos/>**  
**A página da wiki do partido que documenta, detalha e explicita os gastos com TI é a seguinte: <https://wiki.partidopirata.org/wiki/gastos/>**  
**A página da wiki do partido que documenta, detalha e explicita os gastos com TI é a seguinte: <https://wiki.partidopirata.org/wiki/gastos/>**  
**A página da wiki do partido que documenta, detalha e explicita os gastos com TI é a seguinte: <https://wiki.partidopirata.org/wiki/gastos/>**  

Existe uma outra página em construção que era pra ter [informações sobre a infraestrutura de ti](https://wiki.partidopirata.org/wiki/gastos) mas que tem poucas informações pelo motivo simples de que não existe esforço por parte das pessoas em fornecer e organizar a informação.

O que eu de fato disse e continuo dizendo é que nem o partido nem ninguém está ajudando a manter financeiramente as coisas a não ser as pessoas que estão listadas na tabela de gastos da wiki, que eu gostaria de lembrar que se encontra em **<https://wiki.partidopirata.org/wiki/gastos/>** 
**<https://wiki.partidopirata.org/wiki/gastos/>** 
**<https://wiki.partidopirata.org/wiki/gastos/>** 
**<https://wiki.partidopirata.org/wiki/gastos/>** 
**<https://wiki.partidopirata.org/wiki/gastos/>** 
**<https://wiki.partidopirata.org/wiki/gastos/>** 
**<https://wiki.partidopirata.org/wiki/gastos/>**.

Tem que criar meios pra ajudar as pessoas a pararem de carregar o barco sozinho nas costas. Eu to sempre dizendo isto.

Coisas que funcionam:

* Dar dinheiro;
* Fornecer infraestrutura de rede e sistemas computacionais;
* Criar meios pra ter mais gente sustentando e financiando;

Coisas que **não** funcionam:

* Reclamar que certas pessoas não sabem conversar direito;
* Cobrar ações e atitudes das outras pessoas;
* Fazer nada;
