### ISSUE TITLE
Ferramenta de edição de documentos colaborativa

### ISSUE THREAD

**Issue by desci** [piratas/gti#58]
*Se a pergunta não se aplicar, deixe sem resposta*

### A que site, ferramenta ou coisa esta questão está relacionada?

<https://piratas.hackpad.com>

---

### Descreva a ideia, projeto, sugestão, use quantas palavras quiser ou precisar:

Enviado por e-mail:

> O GTC utilizou por um determinado período o hackpad que está morrendo. Gostaria de solicitar a instalação de um pad livre para o GTC continuar na criação/tradução de texto para o site do Partido.
> Minha sugestão é o Etherpad ou Titanpad mas caso tenha alguma opção viável favor responda este email falando de tal. Caso a ferramenta tenha a mesma usabilidade e facilidade para edições e criações de texto será ótimo também

### Quem vai ser responsável por organizar?

    não sei

**Comment by desci** [comment]
Titanpad é etherpad lite

**Comment by desci** [comment]
Enquanto isso ainda ta no ar a conta de organização no pad do partido alemão: <https://piratasbr.piratenpad.de/>

E tem [essa lista](https://we.riseup.net/iikb/ferramentas#etherpad) com alternativas

**Comment by mtoledo62** [comment]
Tem o https://cryptpad.fr/ que é open source, criptografado e com muitas funções

**Comment by corvolino** [comment]
Vale deixar registrado que a administração do pad será do GTC e não do GTI.

**Comment by desci** [comment]
@corvolino Isto é confuso. Defina "administração"

**Comment by diegor2** [comment]
subi um pad aqui http://iniciativa.hopto.org:42091/, depois vou colocar no dominio oficial, mas já dá para ir usando e testando.

**Comment by diegor2** [comment]
Documentado aqui https://wiki.partidopirata.org/wiki/infra/

**Comment by desci** [comment]
Usei o subdomínio *etherpad* pra isto.

[certificado](https://github.com/piratas/scripts.d/commit/c3fc740b2ae91ec641e654f582de0684eddb513e)

[proxy](https://github.com/piratas/nginx.d/commit/584b70e28bf5292ec5cc572c1e398f8b42fa1451#diff-2c1121b6cbbb315e8d3a93e14ec2ce72)

**Comment by diegor2** [comment]
Senha de admin foi enviada para comunicação@partidopirata.org (no dia 29/05/17)
