### ISSUE TITLE
Apontar subdomínio para gh-pages

### ISSUE THREAD

**Issue by dseeker** [piratas/gti#6]
Proponho apontar
http://gti.partidopirata.org/
para
http://piratas.github.io/gti/

**Comment by desci** [comment]
Eu estava fazendo o [formulário do gti](https://github.com/piratas/gti2py) que serve para subsidiar [este projeto](https://www.loomio.org/d/svmYCHka/defini-o-de-um-fluxo-de-comunica-o-entre-os-grupos) e está anunciado [neste tópico](https://www.loomio.org/d/dZFh089M/).

A ideia era usar aquele framework (web2py) pra botar nesse domínio (`gti.partidopirata.org`) e ir adicionando as outras coisas lá mesmo. Mas como tem mais atividade, já tem coisas em php, no github e em python, então não da pra condicionar tudo num framework só.

No [servidor da kimsufi](https://we.riseup.net/iikb/iti#entwickler-iikb-org) já está tudo configurado pra funcionar em sub-sub domínios ou sub-diretórios.

Se eu não me engano, inclusive já botei lá uma regra pra fazer um proxy_pass para `piratas.github.io/gti/`.

Minha tentativa de fazer o redirecionamento:

\@desobedientecivil
> Vei
> Fizemos a reunião do gti hoje
> Tem como botar mais um registro lá no arquivo de zona
> CNAME gti gti.piratas.iikb.org.
> Com ponto no final mesmo

\@Marcelo_h
> Cara tô de férias longe de um PC, só depois do carnaval, mas pode pedir pro gti Reinaldo, Rafael e outros

\@AllanDaemon
> Eu me chamo Reynaldo. Mas meu HD deu pau e to sem meus arquivos agora

**Comment by dseeker** [comment]
e pq nao utilizar o proprio github como "formulário"?
direciona para os interessados criarem um markdown em alguma pasta daqui tipo "inscrições" e pedir um PR.
qual a necessidade de criar um sistema só pra isso? 
me parecer over engineering proximo do que foi o S.I.M.

**Comment by desci** [comment]
> e pq nao utilizar o proprio github como "formulário"?

Porque o github não tem sistema de formulário.

Porque ninguém que quer colaborar com o partido deve ser obrigado a criar conta no github.

O sistema já está criado, over engineering é esperar todo mundo criar conta no github e aprender a usar o sistema, enquanto um formulário está em vigor na internet desde o tempo do SSI.

**Comment by desci** [comment]
Está funcional em http://gti.piratas.xyz/github/

A partir do momento em que `gti.partidopirata.org` apontar para `piratas.iikb.org`, estará funcional em http://gti.partidopirata.org/github/

**Comment by desci** [comment]
Quem foi que apontou `piratas.github.io/gti` **para** `gti.partidopirata.org`?

O subdomínio `gti` de `partidopirata.org` **não existe**.

A ideia proposta originalmente aqui era fazer o **contrário**.

Não quero saber quem foi, quero saber como fazer pra reverter isto, e se alguém se prontifica.

**Comment by desci** [comment]
Agora o link `gti.pirata.xyz/github``está apontando para um *pageok* da godaddy.

**Comment by dseeker** [comment]
muito estranho, será por causa disso? https://github.com/piratas/gti/blob/gh-pages/CNAME

**Comment by desci** [comment]
Deu, agora que eu tenho acesso à zona DNS ta com SSL da Let's Encrypt e funcional em:

**<https://gti.partidopirata.org/github>**

**Comment by desci** [comment]
Criei um site para **<https://gti.partidopirata.org>** cujo código fonte está [aqui no github](https://github.com/piratas/gti-site).

Te contempla, @dseeker?

Peço atenção ao fato do site do github.io ter ficado meio desatualizado

**Comment by iannsp** [comment]
Ótimo, obrigado @desci 
esse final de semana, vou dar uma olhada no nosso gh-pages.
Vamos aproveitar o evento de quinta-feira para definir os proximos passos na gh-pages e wiki.

**Comment by desci** [comment]
Agora eu tenho que aprender a usar o blog ou instalar o jekyll neste repositório
