### ISSUE TITLE
Mostrar imagem grande no twitter card do blog

### ISSUE THREAD

**Issue by diegor2** [piratas/gti#66]
*Se a pergunta não se aplicar, deixe sem resposta*

### A que site, ferramenta ou coisa esta questão está relacionada?

http://partidopirata.org/
https://github.com/piratas/piratas-site

---

### Descreva a ideia, projeto, sugestão, use quantas palavras quiser ou precisar:

Fazer os links do blog (site principal) mostrar uma imagem grande no twitter e nas ferramentas que usam o padrão "twitter card" para gerar uma prévia do conteúdo, conforme descrito aqui: https://dev.twitter.com/cards/types/summary-large-image

### Quem vai ser responsável por organizar?

@diegor2

---

### O que tu tentou fazer?

    Postar um link do blog no twitter.

### O que deveria acontecer?

    Mostrar uma imagem grande e bonita igual essa

![image](https://user-images.githubusercontent.com/921798/26854368-3e636e98-4aec-11e7-982c-c6814a9dc411.png)

### O que aconteceu?

    Aparece uma imagem pequena e cortada:

![image](https://user-images.githubusercontent.com/921798/26854356-2c323e20-4aec-11e7-92ac-aeb9ab23fec7.png)

### Como reproduzir o problema?

Jogar esse link: https://partidopirata.org/por-que-professores-estao-escrevendo-porcaria-que-ninguem-le/ (ou de qualquer outro post do blog) no https://cards-dev.twitter.com/validator

**Comment by diegor2** [comment]
O blog atualmente usa o plugin oficial do Twitter (https://wordpress.org/plugins/twitter/) que por padrão gera o twtter card do tipo `summary` (com a imagem pequena, conforme https://dev.twitter.com/cards/types/summary).

> The plugin generates markup for a Twitter Card **summary** template for most of your site’s pages by default.

Pelo que tá escrito em https://dev.twitter.com/web/wordpress/cards tem que implementar um filtro `twitter_card_type` que retorne `summary_large_image`. Talvez tenha algum plugin melhor que já resolva isso, mas como não achei a solução mais simples parece ser alterar o template.

**Comment by desci** [comment]
Não temos acordo e um fluxo bem definido pra lidar com os plugins do site do partido, atualmente cada um faz o que quiser e o site já saiu do ar três vezes por consequência disto.

**Comment by diegor2** [comment]
@desci Outra solução ainda mais fácil é fazer um fork do plugin corrigindo isso e deixar que quem quiser e puder instale no WordPress.

**Comment by desci** [comment]
@diegor2 funciona pra mim

Mas se é pra deixar as pessoas fazerem o que quiserem e puderem, não tem pra que ter GTI.

Quando o site sai do ar por causa dessa bagunça, ficam enchendo o saco e cobrando pressa pra botar no ar de novo, mas na hora de valorizar o trabalho que se faz pra deixar as coisas organizadas e mais fáceis de administrar, é o contrário que acontece.

**Comment by diegor2** [comment]
Resolveram mexendo direto no código em produção.

**Comment by DanLinus** [comment]
parece que deu certo o problema

**Comment by desci** [comment]
Eu faria o seguinte:

1. Alterar o código pra refletir a mudança necessária;
1. Ainda alterando o código, criar meios para configurar qual o formato desejado, de forma que seja possível escolher facilmente;
1. Documentar as alterações em um repositório próprio;
1. Enviar as melhorias para o repositório original, pra ajudar outras pessoas que tenham a mesma necessidade;

**Comment by anupritaisno1** [comment]
@DanLinus I fixed it
