### ISSUE TITLE
Mumble fora do ar

### ISSUE THREAD

**Issue by mtoledo62** [piratas/gti#67]
### A que site, ferramenta ou coisa esta questão está relacionada?

Mumble

---

### O que tu tentou fazer?

usar

### O que deveria acontecer?

conectar

### O que aconteceu?

conexão recusada

### Como reproduzir o problema?

tentando conectar no mumble.partidopirata.org ou no endereço ipv4 e ipv6 indicados no site

**Comment by desci** [comment]
``` bash
desci@entwickler:~$ sudo systemctl -l status murmur
● murmur.service - mumble server
   Loaded: loaded (/lib/systemd/system/murmur.service; enabled)
   Active: inactive (dead) since Sáb 2017-06-03 12:50:42 CEST; 3 weeks 4 days ago
 Main PID: 0 (code=exited, status=0/SUCCESS)
```

Desde o início do mês ta fora do ar, pelo jeito ninguém mais se importa

**Comment by desci** [comment]
Botei o mumble na lista de um [script](https://notabug.org/desci/scripts/src/master/watchdog.bash) que fica monitorando serviços do systemd

Pra verificar de 5 em 5 minutos:

``` bash
desci@entwickler:~$ sudo crontab -l | grep -e watchdog
*/5     *       *       *       *       /bin/bash /home/iuri/bin/watchdog.bash
```
