### ISSUE TITLE
Tags com nivel de dificuldade

### ISSUE THREAD

**Issue by daviortega** [piratas/gti#70]
## Tags com niveis de dificuldade e prioridade

Levando em consideracao que:
* Vira e mexe chega gente caindo de paraquedas no GTI
* 10% dessa turma quer colocar a mao na massa mas nao sabe como
* Os issues do GTI jah estao centralizados aqui

Podemos melhorar a eficiencia e captar essa "mao-de-obra" que chega no partido, de forma decentralizada, se tiver um guia de tags padronizadas.

Como esse aqui: https://github.com/servo/servo/wiki/Tag-label-names-and-definitions

Jah de cara eu proponho 5 niveis de dificuldade: N-1, N-2, N-3, N-4, N-5.

N-1 seriam as tarefas que qualquer pessoa que saiba digitar no computador pode resolver
N-2 tarefas que pessoas que saibam basico de programacao consegue fazer
N-3 tarefas que pessoas precisam saber programar bem
N-4 tarefas que pessoas precisam saber programar bem e entender do que se trata
N-5 tarefas que soh quem anda por aqui a mais de 6 meses pode resolver.

E tambem proponho prioridade: P-1, P-2, P-3, P-4, P-5

P-1 faz quando der, se nao deu beleza
P-2 Faz quando der, mas tem que dar.
P-3 Tem que fazer pq eh importante
P-4 Se nao fizer o mundo acaba
P-5 Se nao fizer o mundo acaba nas proximas 12h

## Perguntas frequentes

> P: Pra que isso ?
> R: Pra que quando chegar gente nova (ou velha) com tempo e vontade de ajudar, poder ser guiado para os issues no github e nao ficar completamente perdido. Assim, um iniciante que queira aprender a programar pode iniciar as tarefas N-2 e os mais experientes vao ajudando. Todo mundo ganha, ninguem precisa ficar passando a mao na cabeca ou pegando na mao de ninguem. Quem nao sabe nada, comeca pelas N-1.

> P: Quem define a prioridade e o nivel de dificuldade da tarefa? 
> R: Quem postou a tarefa. 

> P: Mas e se eu nao concordo com a prioridade que a Alice colocou?
> R: Nao faca a tarefa

> P: Eu vou por todos os issues que eu fizer como P-5
> R: Tags sao soh guidelines, as pessoas vao entrar e ver que nao eh tao urgente assim e vc vai perder a credibilidade que talvez vc jah tivesse.

**Comment by daviortega** [comment]
Can't do it without the correct permissions, add me as a contributor :)

**Comment by desci** [comment]
@daviortega fala em português, tchê

**Comment by daviortega** [comment]
@desci tah bom, eu nao consigo pegar esse issue pra fazer se nao for colaborador. Adiciona eu aih ou vc quer que eu abra outro issue pra isso? ;)

**Comment by desci** [comment]
Pra posteridade, se alguém mais tiver dificuldade pra conseguir ser parte da organização do github - da mesma forma que aconteceu com **todo mundo** que entrou aqui - procura em https://help.github.com como é que se faz pra aceitar o convite, da mesma forma que **ninguém** fez

**Comment by daviortega** [comment]
Done, tah lah no PR #72 para incluir um manualzinho sobre as tags. Vou fechar.
