### ISSUE TITLE
Certificado de segurança do site

### ISSUE THREAD

**Issue by bemfica** [piratas/gti#75]
*Se a pergunta não se aplicar, deixe sem resposta*

### A que site, ferramenta ou coisa esta questão está relacionada?

    Site do partido (e provavelmente todos os sites que usam o mesmo gerador de certificados)

---

### Descreva a ideia, projeto, sugestão, use quantas palavras quiser ou precisar:

    não sei

### Quem vai ser responsável por organizar?

    não sei

---

### O que tu tentou fazer?

    acesso ao site do partido. 

### O que deveria acontecer?

    guess what

### O que aconteceu?

    Está dando um aviso de que o certificado expirou hoje pela manhã. Achei o timing interessante.

### Como reproduzir o problema?

    Acessar o site do partido. Por navegadores com webkit dá pra acessar (tentei pelo Chrome ao menos), ele dá uma mensagem de alerta e lá embaixo mostra a opção de acessar mesmo assim. pelo Firefox não tem como.

**Comment by iuriguilherme** [comment]
@bemfica certificados da let's encrypt renovados
